### ISSUE TITLE
Error on node v4.2.1

### ISSUE THREAD

**Issue by lschpmn** [siboulet/node-rrd-stream#1]
Get this error, 
"TypeError: Cannot set property length of [object Object] which has only a getter
    at null.<anonymous> (/home/lchapman/rrd-fetch/node_modules/rrd-stream/index.js:92:30)
    at emitNone (events.js:72:20)
    at RRDRRA.emit (events.js:166:7)
    at RRDRRA.push (/home/lchapman/rrd-fetch/node_modules/rrd-stream/index.js:233:10)
    at RRDStream._transform (/home/lchapman/rrd-fetch/node_modules/rrd-stream/index.js:103:14)
    at Transform._read (_stream_transform.js:167:10)
    at Transform._write (_stream_transform.js:155:12)
    at doWrite (_stream_writable.js:292:12)
    at writeOrBuffer (_stream_writable.js:278:5)
    at Writable.write (_stream_writable.js:207:11)
    at ReadStream.ondata (_stream_readable.js:528:20)
    at emitOne (events.js:77:13)
    at ReadStream.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at ReadStream.Readable.push (_stream_readable.js:110:10)
    at onread (fs.js:1748:12)"

on v4.2.1. I just copied and pasted the example.

**Comment by lschpmn** [comment]
Seemed to get things running again by putting "this.buffer = new Buffer(0)" instead of what it was trying to do. Don't know if this has negative effects elsewhere.

**Comment by siboulet** [comment]
@lschpmn thanks for reporting this. I'll try to take a look in the next days.
